library(rmarkdown)
render("david_bowie_3.R", output_options = list(self_contained=F, results="asis", dev="svg"), clean=F)
file.copy("david_bowie_3.utf8.md", "../../jmgaguilera.github.io/_posts/2016-03-26-david-bowie-III.markdown", overwrite=T)
fich = list.files("david_bowie_3_files/figure-html/", full.names = T)
file.copy(from=fich, to="../../jmgaguilera.github.io/images/david_bowie_3_files/figure-html/", overwrite=T)
